[package]
name = "rust_simul"
version = "0.1.0"
authors = ["spark"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peroxide = "0.23"
